# UEFI boot entry for the live ISO
# Place on the ESP under /loader/entries/
# %INSTALL_DIR% is replaced by archiso (usually "arch")

title   NexoraOS 2026.1 (Live, default)
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/x86_64/intel-ucode.img
initrd  /%INSTALL_DIR%/boot/x86_64/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% cow_spacesize=4G quiet splash
