[greeter]
theme-name = Nexora-2026
icon-theme-name = Papirus-Dark
font-name = Ubuntu 11
background = /usr/share/nexora/wallpapers/default.png
screensaver-timeout = 0
show-clock = true
clock-format = %H:%M  %a %d %b
keyboard = onscreen
a11y-states = ~keyboard
