title   NexoraOS 2026.1 (Live, low-RAM mode)
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/x86_64/intel-ucode.img
initrd  /%INSTALL_DIR%/boot/x86_64/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% cow_spacesize=1G nomodeset systemd.unit=multi-user.target
