# Calamares displaymanager module — NexoraOS

displaymanagers:
  - lightdm

lightdm:
  configuration_file: /etc/lightdm/lightdm.conf
  greeter_default_session: nexora
  greeter_user: nexora
  autologin:
    - nexora
