# Calamares users module — NexoraOS

defaultGroups:
  - name: wheel
    must_exist: true
  - name: storage
    must_exist: true
  - name: power
    must_exist: true
  - name: network
    must_exist: true
  - name: video
    must_exist: true
  - name: audio
    must_exist: true
  - name: lp
    must_exist: true
  - name: autologin
    must_exist: true
  - name: vboxsf
    must_exist: false
  - name: kvm
    must_exist: false

doAutologin: true

doReusePassword: true

passwordRequirements:
  nonempty: true
  minLength: 1
  maxLength: 200

userShell: /bin/bash

setHostname: EtcFile

writeHostsFile: true
