# Calamares welcome module — NexoraOS

showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false

requirements:
  requiredStorage:    8.0    # GB
  requiredRam:        1.0    # GB (we still install on 1 GB systems in low-RAM mode)
  internetCheckUrl:   https://github.com/salom600/osbeta
  check:
    - storage
    - ram
    - power
    - internet
    - root
  required:
    - storage
    - ram
    - root

# URLs
supportUrl:        https://github.com/salom600/osbeta/issues
knownIssuesUrl:    https://github.com/salom600/osbeta/issues
