[Seat:*]
greeter-session=lightdm-gtk-greeter
greeter-hide-users=false
user-session=nexora
session-wrapper=/etc/lightdm/Xsession
autologin-user=nexora
autologin-session=nexora
autologin-user-timeout=0
allow-guest=false
